name: Go
on: [push, pull_request]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password
  APP_DB_NAME: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go get .
        
      # Start PostgreSQL docker container
      - name: Start postgresql Container
        run: docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=$APP_DB_PASSWORD -e POSTGRES_USER=$APP_DB_USERNAME -e POSTGRES_DB=$APP_DB_NAME -d postgres


      # Add a step to wait until Postgres is ready
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres pg_isready -U ${APP_DB_USERNAME}; do
            sleep 2
          done
          echo "PostgreSQL is ready."

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
